### ISSUE TITLE
`Get-SmartsheetSheet` - Variable Misspelling

### ISSUE THREAD

**Issue by mattcargile** [skywayskase/PSSmartsheet#5]
**Describe the bug**
Looks like this needs to start with `$Script:`
https://github.com/skywayskase/PSSmartsheet/blob/ca67d97d1c5534231210225e75727d0f50e1d66e/Source/Public/Sheets/Get-SmartsheetSheet.ps1#L56

**To Reproduce**
Attempt to run `Get-SmartsheetSheet`

**Expected behavior**
Output smartsheet list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 21H1
 - Powershell Version 7.2.5
 - Module Version 0.1.4

**Additional context**
Love the module. Thanks for the work!

**Comment by skywayskase** [comment]
Well huh, how about that. Good catch, I'll get that fixed and updated shortly.
